### ISSUE TITLE
Bug: When no data, last reading remains

### ISSUE THREAD

**Issue by Delubear** [Delubear/GlucoseTray#21]
When not receiving data, need to display either 0 or another message rather continue showing our last recorded result.

**Comment by Delubear** [comment]
Clarifying that this is when the DexCom is not outputting data.  Loss of PC internet works as expected.

**Comment by fabriziocasellato** [comment]
Hi Chris, We're a Non Profit Association. We are developing a project and I'd like to collaborate with your software (GlucoseTray). May you please contact us to: info@deebee.it?
Thank you very much :)

**Comment by Delubear** [comment]
ERR] Nightscout fetching failed or received incorrect format. System.AggregateException: One or more errors occurred. (The requested name is valid, but no data of the requested type was found.)
 ---> System.Net.Http.HttpRequestException: The requested name is valid, but no data of the requested type was found.
 ---> System.Net.Sockets.SocketException (11004): The requested name is valid, but no data of the requested type was found.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Dexcom.Fetch.GlucoseFetchService.GetFetchResultFromNightscout(GlucoseFetchResult fetchResult)

**Comment by Delubear** [comment]
Fixed in latest PR. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
